In [1]:
import statsmodels.api as sm
from statsmodels.formula.api import ols

In [2]:
moore= sm.datasets.get_rdataset('Moore', 'carData',cache=True)

In [8]:
data=moore.data
data

   partner.status  conformity fcategory  fscore
0             low           8       low      37
1             low           4      high      57
2             low           8      high      65
3             low           7       low      20
4             low          10       low      36
5             low           6       low      18
6             low          12    medium      51
7             low           4    medium      44
8             low          13       low      31
9             low          12       low      36
10            low           4    medium      42
11            low          13      high      56
12            low           7       low      28
13            low           9    medium      43
14            low           9      high      65
15            low          24      high      57
16            low           6       low      28
17            low           7      high      61
18            low          23      high      57
19            low          13      high      55
20            low           8       low      17
21            low          12       low      35
22           high          19      high      68
23           high          12    medium      41
24           high          21       low      16
25           high           9      high      63
26           high          23       low      15
27           high           7      high      54
28           high          17    medium      48
29           high          14    medium      42
30           high          11      high      59
31           high          16    medium      45
32           high          15       low      30
33           high          20    medium      44
34           high           8    medium      42
35           high          12       low      22
36           high          14      high      52
37           high          14    medium      42
38           high          17    medium      41
39           high           7    medium      50
40           high          17    medium      39
41           high          13      high      57
42           high          16       low      35
43           high          10      high      52
44           high          15    medium      44

In [4]:
data=data.rename(columns={'partner.status':'partner_status'})

In [5]:
moore_lm= ols('conformity~C(fcategory,Sum)* C(partner_status, Sum)',data=data).fit()

In [6]:
table=sm.stats.anova_lm(moore_lm,typ=2)

In [7]:
print(table)

                                              sum_sq    df          F  \
C(fcategory, Sum)                          11.614700   2.0   0.276958
C(partner_status, Sum)                    212.213778   1.0  10.120692
C(fcategory, Sum):C(partner_status, Sum)  175.488928   2.0   4.184623
Residual                                  817.763961  39.0        NaN

                                            PR(>F)
C(fcategory, Sum)                         0.759564
C(partner_status, Sum)                    0.002874
C(fcategory, Sum):C(partner_status, Sum)  0.022572
Residual                                       NaN